export const counties = [
  'Alba', 'Arad', 'Argeș', 'Bacău', 'Bihor', 'Bistrița-Năsăud', 'Botoșani', 'Brașov',
  'Brăila', 'București', 'Buzău', 'Caraș-Severin', 'Călărași', 'Cluj', 'Constanța',
  'Covasna', 'Dâmbovița', 'Dolj', 'Galați', 'Giurgiu', 'Gorj', 'Harghita', 'Hunedoara',
  'Ialomița', 'Iași', 'Ilfov', 'Maramureș', 'Mehedinți', 'Mureș', 'Neamț', 'Olt',
  'Prahova', 'Satu Mare', 'Sălaj', 'Sibiu', 'Suceava', 'Teleorman', 'Timiș', 'Tulcea',
  'Vaslui', 'Vâlcea', 'Vrancea'
];

export const citiesByCounty: { [key: string]: string[] } = {
  'Alba': ['Alba Iulia', 'Aiud', 'Blaj', 'Sebeș', 'Cugir'],
  'Arad': ['Arad', 'Lipova', 'Ineu', 'Chișineu-Criș', 'Pecica'],
  'Argeș': ['Pitești', 'Câmpulung', 'Curtea de Argeș', 'Mioveni', 'Costești'],
  'Bacău': ['Bacău', 'Onești', 'Moinești', 'Comănești', 'Buhuși'],
  'Bihor': ['Oradea', 'Salonta', 'Marghita', 'Beiuș', 'Aleșd'],
  'Bistrița-Năsăud': ['Bistrița', 'Năsăud', 'Beclean', 'Sângeorz-Băi'],
  'Botoșani': ['Botoșani', 'Dorohoi', 'Săveni', 'Darabani', 'Flămânzi'],
  'Brașov': ['Brașov', 'Făgăraș', 'Săcele', 'Zărnești', 'Codlea'],
  'Brăila': ['Brăila', 'Ianca', 'Însurăței', 'Făurei'],
  'București': ['Sector 1', 'Sector 2', 'Sector 3', 'Sector 4', 'Sector 5', 'Sector 6'],
  'Buzău': ['Buzău', 'Râmnicu Sărat', 'Nehoiu', 'Pogoanele', 'Pătârlagele'],
  'Caraș-Severin': ['Reșița', 'Caransebeș', 'Oravița', 'Moldova Nouă', 'Bocșa'],
  'Călărași': ['Călărași', 'Oltenița', 'Budești', 'Lehliu Gară', 'Fundulea'],
  'Cluj': ['Cluj-Napoca', 'Turda', 'Dej', 'Câmpia Turzii', 'Gherla'],
  'Constanța': ['Constanța', 'Medgidia', 'Mangalia', 'Năvodari', 'Cernavodă'],
  'Covasna': ['Sfântu Gheorghe', 'Târgu Secuiesc', 'Covasna', 'Baraolt', 'Întorsura Buzăului'],
  'Dâmbovița': ['Târgoviște', 'Moreni', 'Pucioasa', 'Găești', 'Titu'],
  'Dolj': ['Craiova', 'Băilești', 'Calafat', 'Filiași', 'Segarcea'],
  'Galați': ['Galați', 'Tecuci', 'Târgu Bujor', 'Berești'],
  'Giurgiu': ['Giurgiu', 'Bolintin-Vale', 'Mihăilești'],
  'Gorj': ['Târgu Jiu', 'Motru', 'Rovinari', 'Bumbești-Jiu', 'Târgu Cărbunești'],
  'Harghita': ['Miercurea Ciuc', 'Odorheiu Secuiesc', 'Gheorgheni', 'Toplița', 'Cristuru Secuiesc'],
  'Hunedoara': ['Deva', 'Hunedoara', 'Petroșani', 'Orăștie', 'Brad'],
  'Ialomița': ['Slobozia', 'Fetești', 'Urziceni', 'Țăndărei'],
  'Iași': ['Iași', 'Pașcani', 'Hârlău', 'Târgu Frumos', 'Podu Iloaiei'],
  'Ilfov': ['Buftea', 'Otopeni', 'Voluntari', 'Pantelimon', 'Popești-Leordeni'],
  'Maramureș': ['Baia Mare', 'Sighetu Marmației', 'Borșa', 'Vișeu de Sus', 'Târgu Lăpuș'],
  'Mehedinți': ['Drobeta-Turnu Severin', 'Orșova', 'Strehaia', 'Vânju Mare', 'Baia de Aramă'],
  'Mureș': ['Târgu Mureș', 'Sighișoara', 'Reghin', 'Târnăveni', 'Luduș'],
  'Neamț': ['Piatra Neamț', 'Roman', 'Târgu Neamț', 'Bicaz', 'Roznov'],
  'Olt': ['Slatina', 'Caracal', 'Corabia', 'Balș', 'Scornicești'],
  'Prahova': ['Ploiești', 'Câmpina', 'Băicoi', 'Breaza', 'Sinaia'],
  'Satu Mare': ['Satu Mare', 'Carei', 'Negrești-Oaș', 'Tășnad', 'Ardud'],
  'Sălaj': ['Zalău', 'Șimleu Silvaniei', 'Jibou', 'Cehu Silvaniei'],
  'Sibiu': ['Sibiu', 'Mediaș', 'Cisnădie', 'Avrig', 'Agnita'],
  'Suceava': ['Suceava', 'Fălticeni', 'Rădăuți', 'Câmpulung Moldovenesc', 'Vatra Dornei'],
  'Teleorman': ['Alexandria', 'Roșiorii de Vede', 'Turnu Măgurele', 'Zimnicea', 'Videle'],
  'Timiș': ['Timișoara', 'Lugoj', 'Sânnicolau Mare', 'Jimbolia', 'Buziaș'],
  'Tulcea': ['Tulcea', 'Babadag', 'Măcin', 'Isaccea', 'Sulina'],
  'Vaslui': ['Vaslui', 'Bârlad', 'Huși', 'Negrești'],
  'Vâlcea': ['Râmnicu Vâlcea', 'Drăgășani', 'Băbeni', 'Călimănești', 'Horezu'],
  'Vrancea': ['Focșani', 'Adjud', 'Mărășești', 'Odobești', 'Panciu']
};